package com.map.domain;

public class BoardDto {
	/*	
	CREATE TABLE TBL_BOARD(
			BNO NUMBER(10, 0),
			WRITER VARCHAR2(50) NOT NULL,
			TITLE VARCHAR2(200) NOT NULL,
			CONTENT VARCHAR2(2000) NOT NULL,
			REGDATE DATE DEFAULT SYSDATE,
			UPDATEDATE DATE DEFAULT SYSDATE
		);
	 */
}
